# Generated by Django 3.2 on 2026-03-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
